/** Navigation lifecycle event names */
export const EVENTS = {
  BEFORE_NAVIGATE: 'beforenavigate',
  ROUTE_CHANGE: 'routechange',
  AFTER_NAVIGATE: 'afternavigate',
  BEFORE_RENDER: 'beforerender',
  AFTER_RENDER: 'afterrender',
  ERROR: 'error',
  NOT_FOUND: 'notfound',
  LOADING: 'loading',
  READY: 'ready',
  DESTROY: 'destroy',
  PLUGIN_INSTALL: 'plugininstall',
  PLUGIN_EJECT: 'plugineject',
  ACCESS_DENIED: 'accessdenied',
  MAINTENANCE: 'maintenance',
}

export const SEGMENT_TYPES = {
  STATIC: 'static',
  DYNAMIC: 'dynamic',
  CATCH_ALL: 'catch-all',
  OPTIONAL_CATCH_ALL: 'optional-catch-all',
  GROUP: 'group',
}

export const PARAM_PATTERNS = {
  DYNAMIC: /^\[([^\]]+)\]$/,
  CATCH_ALL: /^\[\.\.\.([^\]]+)\]$/,
  OPTIONAL_CATCH_ALL: /^\[\[\.\.\.([^\]]+)\]\]$/,
  GROUP: /^\(([^)]+)\)$/,
}

export const PATTERN_SCORES = {
  [SEGMENT_TYPES.STATIC]: 100,
  [SEGMENT_TYPES.DYNAMIC]: 10,
  [SEGMENT_TYPES.CATCH_ALL]: 1,
  [SEGMENT_TYPES.OPTIONAL_CATCH_ALL]: 0,
  [SEGMENT_TYPES.GROUP]: 0,
}

/** HTTP status codes used for error handling */
export const HTTP_STATUS = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  CLIENT_CLOSED_REQUEST: 499,
}

/** Human-readable descriptions for HTTP status codes */
export const HTTP_STATUS_TEXT = {
  400: 'Bad Request',
  401: 'Unauthorized',
  403: 'Forbidden',
  404: 'Not Found',
  405: 'Method Not Allowed',
  406: 'Not Acceptable',
  408: 'Request Timeout',
  409: 'Conflict',
  410: 'Gone',
  411: 'Length Required',
  412: 'Precondition Failed',
  413: 'Payload Too Large',
  414: 'URI Too Long',
  415: 'Unsupported Media Type',
  416: 'Range Not Satisfiable',
  417: 'Expectation Failed',
  418: "I'm a Teapot",
  421: 'Misdirected Request',
  422: 'Unprocessable Entity',
  423: 'Locked',
  424: 'Failed Dependency',
  425: 'Too Early',
  426: 'Upgrade Required',
  428: 'Precondition Required',
  429: 'Too Many Requests',
  431: 'Request Header Fields Too Large',
  451: 'Unavailable For Legal Reasons',
  500: 'Internal Server Error',
  501: 'Not Implemented',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
  504: 'Gateway Timeout',
  505: 'HTTP Version Not Supported',
  506: 'Variant Also Negotiates',
  507: 'Insufficient Storage',
  508: 'Loop Detected',
  510: 'Not Extended',
  511: 'Network Authentication Required',
}

/** Error group categories for fallback handling */
export const ERROR_GROUPS = {
  CLIENT_ERROR: 'client-error',
  SERVER_ERROR: 'server-error',
}

/** Error group membership (maps status to group) */
export const ERROR_GROUP_MAP = {
  400: ERROR_GROUPS.CLIENT_ERROR,
  401: ERROR_GROUPS.CLIENT_ERROR,
  403: ERROR_GROUPS.CLIENT_ERROR,
  404: ERROR_GROUPS.CLIENT_ERROR,
  405: ERROR_GROUPS.CLIENT_ERROR,
  406: ERROR_GROUPS.CLIENT_ERROR,
  408: ERROR_GROUPS.CLIENT_ERROR,
  409: ERROR_GROUPS.CLIENT_ERROR,
  410: ERROR_GROUPS.CLIENT_ERROR,
  411: ERROR_GROUPS.CLIENT_ERROR,
  412: ERROR_GROUPS.CLIENT_ERROR,
  413: ERROR_GROUPS.CLIENT_ERROR,
  414: ERROR_GROUPS.CLIENT_ERROR,
  415: ERROR_GROUPS.CLIENT_ERROR,
  416: ERROR_GROUPS.CLIENT_ERROR,
  417: ERROR_GROUPS.CLIENT_ERROR,
  418: ERROR_GROUPS.CLIENT_ERROR,
  421: ERROR_GROUPS.CLIENT_ERROR,
  422: ERROR_GROUPS.CLIENT_ERROR,
  423: ERROR_GROUPS.CLIENT_ERROR,
  424: ERROR_GROUPS.CLIENT_ERROR,
  425: ERROR_GROUPS.CLIENT_ERROR,
  426: ERROR_GROUPS.CLIENT_ERROR,
  428: ERROR_GROUPS.CLIENT_ERROR,
  429: ERROR_GROUPS.CLIENT_ERROR,
  431: ERROR_GROUPS.CLIENT_ERROR,
  451: ERROR_GROUPS.CLIENT_ERROR,
  500: ERROR_GROUPS.SERVER_ERROR,
  501: ERROR_GROUPS.SERVER_ERROR,
  502: ERROR_GROUPS.SERVER_ERROR,
  503: ERROR_GROUPS.SERVER_ERROR,
  504: ERROR_GROUPS.SERVER_ERROR,
  505: ERROR_GROUPS.SERVER_ERROR,
  506: ERROR_GROUPS.SERVER_ERROR,
  507: ERROR_GROUPS.SERVER_ERROR,
  508: ERROR_GROUPS.SERVER_ERROR,
  510: ERROR_GROUPS.SERVER_ERROR,
  511: ERROR_GROUPS.SERVER_ERROR,
}

export const DEFAULT_CONFIG = {
  target: '#app',
  basePath: '',
  useHash: false,
  scrollToTop: true,
  prefetch: true,
  cacheRoutes: true,
  maxCacheSize: 50,
  navigationTimeout: 15000,
  titleTemplate: '%s — SafaRouter',
  transitionDuration: 0,
  transitionEnterClass: 'page-enter',
  transitionExitClass: 'page-exit',
  transitionEnterActiveClass: 'page-enter-active',
  transitionExitActiveClass: 'page-exit-active',
  plugins: [],
  errors: {
    enabled: true,
    stackTraces: true,
    pageDir: null,
    status: {},
    groups: {
      'client-error': { enabled: true, page: null, component: null },
      'server-error': { enabled: true, page: null, component: null },
    },
    redirect: {},
  },
  access: {
    blocked: [],
    ignored: [],
    allowed: [],
    mode: 'blocklist',
  },
  realtime: {
    enabled: false,
    mode: 'sse',
    url: '/__realtime',
    interval: 2000,
    onChange: null,
  },
  maintenanceMode: {
    enabled: false,
    page: null,
    component: null,
    allowedPaths: ['/login', '/assets/**'],
  },
  errorLogging: {
    enabled: true,
    handler: null,
  },
}
